changed readiness

diff --git a/elasticsearch/templates/statefulset.yaml b/elasticsearch/templates/statefulset.yaml
--- a/elasticsearch/templates/statefulset.yaml
+++ b/elasticsearch/templates/statefulset.yaml
@@ -236,71 +236,71 @@ spec:
 {{ toYaml .Values.securityContext | indent 10 }}
         image: "{{ .Values.image }}:{{ .Values.imageTag }}"
         imagePullPolicy: "{{ .Values.imagePullPolicy }}"
-        readinessProbe:
-          exec:
-            command:
-              - bash
-              - -c
-              - |
-                set -e
+#         readinessProbe:
+#           exec:
+#             command:
+#               - bash
+#               - -c
+#               - |
+#                 set -e
 
-                # Exit if ELASTIC_PASSWORD in unset
-                if [ -z "${ELASTIC_PASSWORD}" ]; then
-                  echo "ELASTIC_PASSWORD variable is missing, exiting"
-                  exit 1
-                fi
+#                 # Exit if ELASTIC_PASSWORD in unset
+#                 if [ -z "${ELASTIC_PASSWORD}" ]; then
+#                   echo "ELASTIC_PASSWORD variable is missing, exiting"
+#                   exit 1
+#                 fi
 
-                # If the node is starting up wait for the cluster to be ready (request params: "{{ .Values.clusterHealthCheckParams }}" )
-                # Once it has started only check that the node itself is responding
-                START_FILE=/tmp/.es_start_file
+#                 # If the node is starting up wait for the cluster to be ready (request params: "{{ .Values.clusterHealthCheckParams }}" )
+#                 # Once it has started only check that the node itself is responding
+#                 START_FILE=/tmp/.es_start_file
 
-                # Disable nss cache to avoid filling dentry cache when calling curl
-                # This is required with Elasticsearch Docker using nss < 3.52
-                export NSS_SDB_USE_CACHE=no
+#                 # Disable nss cache to avoid filling dentry cache when calling curl
+#                 # This is required with Elasticsearch Docker using nss < 3.52
+#                 export NSS_SDB_USE_CACHE=no
 
-                http () {
-                  local path="${1}"
-                  local args="${2}"
-                  set -- -XGET -s
+#                 http () {
+#                   local path="${1}"
+#                   local args="${2}"
+#                   set -- -XGET -s
 
-                  if [ "$args" != "" ]; then
-                    set -- "$@" $args
-                  fi
+#                   if [ "$args" != "" ]; then
+#                     set -- "$@" $args
+#                   fi
 
-                  set -- "$@" -u "elastic:${ELASTIC_PASSWORD}"
+#                   set -- "$@" -u "elastic:${ELASTIC_PASSWORD}"
 
-                  curl --output /dev/null -k "$@" "{{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}${path}"
-                }
+#                   curl --output /dev/null -k "$@" "{{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}${path}"
+#                 }
 
-                if [ -f "${START_FILE}" ]; then
-                  echo 'Elasticsearch is already running, lets check the node is healthy'
-                  HTTP_CODE=$(http "/" "-w %{http_code}")
-                  RC=$?
-                  if [[ ${RC} -ne 0 ]]; then
-                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}/ failed with RC ${RC}"
-                    exit ${RC}
-                  fi
-                  # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
-                  if [[ ${HTTP_CODE} == "200" ]]; then
-                    exit 0
-                  elif [[ ${HTTP_CODE} == "503" && "{{ include "elasticsearch.esMajorVersion" . }}" == "6" ]]; then
-                    exit 0
-                  else
-                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}/ failed with HTTP code ${HTTP_CODE}"
-                    exit 1
-                  fi
+#                 if [ -f "${START_FILE}" ]; then
+#                   echo 'Elasticsearch is already running, lets check the node is healthy'
+#                   HTTP_CODE=$(http "/" "-w %{http_code}")
+#                   RC=$?
+#                   if [[ ${RC} -ne 0 ]]; then
+#                     echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}/ failed with RC ${RC}"
+#                     exit ${RC}
+#                   fi
+#                   # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
+#                   if [[ ${HTTP_CODE} == "200" ]]; then
+#                     exit 0
+#                   elif [[ ${HTTP_CODE} == "503" && "{{ include "elasticsearch.esMajorVersion" . }}" == "6" ]]; then
+#                     exit 0
+#                   else
+#                     echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} {{ .Values.protocol }}://127.0.0.1:{{ .Values.httpPort }}/ failed with HTTP code ${HTTP_CODE}"
+#                     exit 1
+#                   fi
 
-                else
-                  echo 'Waiting for elasticsearch cluster to become ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
-                  if http "/_cluster/health?{{ .Values.clusterHealthCheckParams }}" "--fail" ; then
-                    touch ${START_FILE}
-                    exit 0
-                  else
-                    echo 'Cluster is not yet ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
-                    exit 1
-                  fi
-                fi
-{{ toYaml .Values.readinessProbe | indent 10 }}
+#                 else
+#                   echo 'Waiting for elasticsearch cluster to become ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
+#                   if http "/_cluster/health?{{ .Values.clusterHealthCheckParams }}" "--fail" ; then
+#                     touch ${START_FILE}
+#                     exit 0
+#                   else
+#                     echo 'Cluster is not yet ready (request params: "{{ .Values.clusterHealthCheckParams }}" )'
+#                     exit 1
+#                   fi
+#                 fi
+# {{ toYaml .Values.readinessProbe | indent 10 }}
         ports:
         - name: http
           containerPort: {{ .Values.httpPort }}
